//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.14 at 06:32:41 PM EST 
//

package au.edu.swin.ict.road.regulator.bindings;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for JFactIdentifierType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="JFactIdentifierType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="identifierKey" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="identifierValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "JFactIdentifierType", propOrder = { "identifierKey",
	"identifierValue" })
public class JFactIdentifierType {

    @XmlElement(required = true)
    protected String identifierKey;
    @XmlElement(required = true)
    protected String identifierValue;

    /**
     * Gets the value of the identifierKey property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getIdentifierKey() {
	return identifierKey;
    }

    /**
     * Sets the value of the identifierKey property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setIdentifierKey(String value) {
	this.identifierKey = value;
    }

    /**
     * Gets the value of the identifierValue property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getIdentifierValue() {
	return identifierValue;
    }

    /**
     * Sets the value of the identifierValue property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setIdentifierValue(String value) {
	this.identifierValue = value;
    }

}
