//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.14 at 06:32:41 PM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.swin.edu.au/ict/road/regulator/Facts")
package au.edu.swin.ict.road.regulator.bindings;

