//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.01 at 06:11:07 PM EST 
//

package au.edu.swin.ict.road.xml.bindings;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for BehaviorTermType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="BehaviorTermType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TaskRefs" type="{http://www.ict.swin.edu.au/serendip/types}TaskRefsType"/>
 *         &lt;element name="Constraints" type="{http://www.ict.swin.edu.au/serendip/types}ConstraintsType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="extension" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="extends" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="isAbstract" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BehaviorTermType", propOrder = { "taskRefs", "constraints" })
public class BehaviorTermType {

    @XmlElement(name = "TaskRefs", namespace = "http://www.ict.swin.edu.au/serendip/types", required = true)
    protected TaskRefsType taskRefs;
    @XmlElement(name = "Constraints", namespace = "http://www.ict.swin.edu.au/serendip/types")
    protected ConstraintsType constraints;
    @XmlAttribute(required = true)
    protected String id;
    @XmlAttribute
    protected String extension;
    @XmlAttribute(name = "extends")
    protected String _extends;
    @XmlAttribute
    protected Boolean isAbstract;

    /**
     * Gets the value of the taskRefs property.
     * 
     * @return possible object is {@link TaskRefsType }
     * 
     */
    public TaskRefsType getTaskRefs() {
	return taskRefs;
    }

    /**
     * Sets the value of the taskRefs property.
     * 
     * @param value
     *            allowed object is {@link TaskRefsType }
     * 
     */
    public void setTaskRefs(TaskRefsType value) {
	this.taskRefs = value;
    }

    /**
     * Gets the value of the constraints property.
     * 
     * @return possible object is {@link ConstraintsType }
     * 
     */
    public ConstraintsType getConstraints() {
	return constraints;
    }

    /**
     * Sets the value of the constraints property.
     * 
     * @param value
     *            allowed object is {@link ConstraintsType }
     * 
     */
    public void setConstraints(ConstraintsType value) {
	this.constraints = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getId() {
	return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setId(String value) {
	this.id = value;
    }

    /**
     * Gets the value of the extension property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getExtension() {
	return extension;
    }

    /**
     * Sets the value of the extension property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setExtension(String value) {
	this.extension = value;
    }

    /**
     * Gets the value of the extends property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getExtends() {
	return _extends;
    }

    /**
     * Sets the value of the extends property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setExtends(String value) {
	this._extends = value;
    }

    /**
     * Gets the value of the isAbstract property.
     * 
     * @return possible object is {@link Boolean }
     * 
     */
    public boolean isIsAbstract() {
	if (isAbstract == null) {
	    return false;
	} else {
	    return isAbstract;
	}
    }

    /**
     * Sets the value of the isAbstract property.
     * 
     * @param value
     *            allowed object is {@link Boolean }
     * 
     */
    public void setIsAbstract(Boolean value) {
	this.isAbstract = value;
    }

}
