//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.01 at 06:11:07 PM EST 
//

package au.edu.swin.ict.road.xml.bindings;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for ContractType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="ContractType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Types">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;any/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="LinkedFacts" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Fact" type="{http://www.swin.edu.au/ict/road/contract}ContractLinkedFactType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="State" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Terms" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Term" type="{http://www.swin.edu.au/ict/road/term}TermType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Monitors" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Monitor" type="{http://www.swin.edu.au/ict/road/monitor}MonitorRoleType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="RoleAID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RoleBID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ruleFile" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ContractType", namespace = "http://www.swin.edu.au/ict/road/contract", propOrder = {
	"types", "linkedFacts", "state", "terms", "monitors", "roleAID",
	"roleBID", "description" })
public class ContractType {

    @XmlElement(name = "Types", required = true)
    protected ContractType.Types types;
    @XmlElement(name = "LinkedFacts")
    protected ContractType.LinkedFacts linkedFacts;
    @XmlElement(name = "State", required = true)
    protected String state;
    @XmlElement(name = "Terms")
    protected ContractType.Terms terms;
    @XmlElement(name = "Monitors")
    protected ContractType.Monitors monitors;
    @XmlElement(name = "RoleAID", required = true)
    protected String roleAID;
    @XmlElement(name = "RoleBID", required = true)
    protected String roleBID;
    @XmlElement(name = "Description")
    protected String description;
    @XmlAttribute(required = true)
    protected String id;
    @XmlAttribute
    protected String name;
    @XmlAttribute
    protected String type;
    @XmlAttribute(required = true)
    protected String ruleFile;

    /**
     * Gets the value of the types property.
     * 
     * @return possible object is {@link ContractType.Types }
     * 
     */
    public ContractType.Types getTypes() {
	return types;
    }

    /**
     * Sets the value of the types property.
     * 
     * @param value
     *            allowed object is {@link ContractType.Types }
     * 
     */
    public void setTypes(ContractType.Types value) {
	this.types = value;
    }

    /**
     * Gets the value of the linkedFacts property.
     * 
     * @return possible object is {@link ContractType.LinkedFacts }
     * 
     */
    public ContractType.LinkedFacts getLinkedFacts() {
	return linkedFacts;
    }

    /**
     * Sets the value of the linkedFacts property.
     * 
     * @param value
     *            allowed object is {@link ContractType.LinkedFacts }
     * 
     */
    public void setLinkedFacts(ContractType.LinkedFacts value) {
	this.linkedFacts = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getState() {
	return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setState(String value) {
	this.state = value;
    }

    /**
     * Gets the value of the terms property.
     * 
     * @return possible object is {@link ContractType.Terms }
     * 
     */
    public ContractType.Terms getTerms() {
	return terms;
    }

    /**
     * Sets the value of the terms property.
     * 
     * @param value
     *            allowed object is {@link ContractType.Terms }
     * 
     */
    public void setTerms(ContractType.Terms value) {
	this.terms = value;
    }

    /**
     * Gets the value of the monitors property.
     * 
     * @return possible object is {@link ContractType.Monitors }
     * 
     */
    public ContractType.Monitors getMonitors() {
	return monitors;
    }

    /**
     * Sets the value of the monitors property.
     * 
     * @param value
     *            allowed object is {@link ContractType.Monitors }
     * 
     */
    public void setMonitors(ContractType.Monitors value) {
	this.monitors = value;
    }

    /**
     * Gets the value of the roleAID property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getRoleAID() {
	return roleAID;
    }

    /**
     * Sets the value of the roleAID property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setRoleAID(String value) {
	this.roleAID = value;
    }

    /**
     * Gets the value of the roleBID property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getRoleBID() {
	return roleBID;
    }

    /**
     * Sets the value of the roleBID property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setRoleBID(String value) {
	this.roleBID = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDescription() {
	return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setDescription(String value) {
	this.description = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getId() {
	return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setId(String value) {
	this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getName() {
	return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setName(String value) {
	this.name = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getType() {
	return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setType(String value) {
	this.type = value;
    }

    /**
     * Gets the value of the ruleFile property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getRuleFile() {
	return ruleFile;
    }

    /**
     * Sets the value of the ruleFile property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setRuleFile(String value) {
	this.ruleFile = value;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained
     * within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Fact" type="{http://www.swin.edu.au/ict/road/contract}ContractLinkedFactType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "fact" })
    public static class LinkedFacts {

	@XmlElement(name = "Fact", required = true)
	protected List<ContractLinkedFactType> fact;

	/**
	 * Gets the value of the fact property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list
	 * will be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the fact property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getFact().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link ContractLinkedFactType }
	 * 
	 * 
	 */
	public List<ContractLinkedFactType> getFact() {
	    if (fact == null) {
		fact = new ArrayList<ContractLinkedFactType>();
	    }
	    return this.fact;
	}

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained
     * within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Monitor" type="{http://www.swin.edu.au/ict/road/monitor}MonitorRoleType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "monitor" })
    public static class Monitors {

	@XmlElement(name = "Monitor")
	protected List<MonitorRoleType> monitor;

	/**
	 * Gets the value of the monitor property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list
	 * will be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the monitor property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getMonitor().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link MonitorRoleType }
	 * 
	 * 
	 */
	public List<MonitorRoleType> getMonitor() {
	    if (monitor == null) {
		monitor = new ArrayList<MonitorRoleType>();
	    }
	    return this.monitor;
	}

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained
     * within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Term" type="{http://www.swin.edu.au/ict/road/term}TermType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "term" })
    public static class Terms {

	@XmlElement(name = "Term")
	protected List<TermType> term;

	/**
	 * Gets the value of the term property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list
	 * will be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the term property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getTerm().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link TermType }
	 * 
	 * 
	 */
	public List<TermType> getTerm() {
	    if (term == null) {
		term = new ArrayList<TermType>();
	    }
	    return this.term;
	}

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained
     * within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;any/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "any" })
    public static class Types {

	@XmlAnyElement(lax = true)
	protected Object any;

	/**
	 * Gets the value of the any property.
	 * 
	 * @return possible object is {@link Object }
	 * 
	 */
	public Object getAny() {
	    return any;
	}

	/**
	 * Sets the value of the any property.
	 * 
	 * @param value
	 *            allowed object is {@link Object }
	 * 
	 */
	public void setAny(Object value) {
	    this.any = value;
	}

    }

}
