//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.01 at 06:11:07 PM EST 
//

package au.edu.swin.ict.road.xml.bindings;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for EventType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="EventType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="isInit" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="isError" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="descr" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EventType")
public class EventType {

    @XmlAttribute(required = true)
    protected String id;
    @XmlAttribute
    protected Boolean isInit;
    @XmlAttribute
    protected Boolean isError;
    @XmlAttribute
    protected String descr;

    /**
     * Gets the value of the id property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getId() {
	return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setId(String value) {
	this.id = value;
    }

    /**
     * Gets the value of the isInit property.
     * 
     * @return possible object is {@link Boolean }
     * 
     */
    public Boolean isIsInit() {
	return isInit;
    }

    /**
     * Sets the value of the isInit property.
     * 
     * @param value
     *            allowed object is {@link Boolean }
     * 
     */
    public void setIsInit(Boolean value) {
	this.isInit = value;
    }

    /**
     * Gets the value of the isError property.
     * 
     * @return possible object is {@link Boolean }
     * 
     */
    public Boolean isIsError() {
	return isError;
    }

    /**
     * Sets the value of the isError property.
     * 
     * @param value
     *            allowed object is {@link Boolean }
     * 
     */
    public void setIsError(Boolean value) {
	this.isError = value;
    }

    /**
     * Gets the value of the descr property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDescr() {
	return descr;
    }

    /**
     * Sets the value of the descr property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setDescr(String value) {
	this.descr = value;
    }

}
