//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.01 at 06:11:07 PM EST 
//

package au.edu.swin.ict.road.xml.bindings;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the au.edu.swin.ict.road.xml.bindings package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    /**
     * Create a new ObjectFactory that can be used to create new instances of
     * schema derived classes for package: au.edu.swin.ict.road.xml.bindings
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TaskType }
     * 
     */
    public TaskType createTaskType() {
	return new TaskType();
    }

    /**
     * Create an instance of {@link ResultMsgsType }
     * 
     */
    public ResultMsgsType createResultMsgsType() {
	return new ResultMsgsType();
    }

    /**
     * Create an instance of {@link FactType }
     * 
     */
    public FactType createFactType() {
	return new FactType();
    }

    /**
     * Create an instance of {@link MessagesType }
     * 
     */
    public MessagesType createMessagesType() {
	return new MessagesType();
    }

    /**
     * Create an instance of {@link SMC.Roles }
     * 
     */
    public SMC.Roles createSMCRoles() {
	return new SMC.Roles();
    }

    /**
     * Create an instance of {@link SMC.PlayerBindings }
     * 
     */
    public SMC.PlayerBindings createSMCPlayerBindings() {
	return new SMC.PlayerBindings();
    }

    /**
     * Create an instance of {@link ApplicationPropertyType }
     * 
     */
    public ApplicationPropertyType createApplicationPropertyType() {
	return new ApplicationPropertyType();
    }

    /**
     * Create an instance of {@link BehaviorTermsType }
     * 
     */
    public BehaviorTermsType createBehaviorTermsType() {
	return new BehaviorTermsType();
    }

    /**
     * Create an instance of {@link RoleLinkedFactType }
     * 
     */
    public RoleLinkedFactType createRoleLinkedFactType() {
	return new RoleLinkedFactType();
    }

    /**
     * Create an instance of {@link BehaviorTermType }
     * 
     */
    public BehaviorTermType createBehaviorTermType() {
	return new BehaviorTermType();
    }

    /**
     * Create an instance of {@link au.edu.swin.ict.road.xml.bindings.Parameter }
     * 
     */
    public au.edu.swin.ict.road.xml.bindings.Parameter createParameter() {
	return new au.edu.swin.ict.road.xml.bindings.Parameter();
    }

    /**
     * Create an instance of {@link ContractType.Terms }
     * 
     */
    public ContractType.Terms createContractTypeTerms() {
	return new ContractType.Terms();
    }

    /**
     * Create an instance of {@link ContractType }
     * 
     */
    public ContractType createContractType() {
	return new ContractType();
    }

    /**
     * Create an instance of {@link ParamsType }
     * 
     */
    public ParamsType createParamsType() {
	return new ParamsType();
    }

    /**
     * Create an instance of {@link OutMsgType }
     * 
     */
    public OutMsgType createOutMsgType() {
	return new OutMsgType();
    }

    /**
     * Create an instance of {@link ParamsType.Parameter }
     * 
     */
    public ParamsType.Parameter createParamsTypeParameter() {
	return new ParamsType.Parameter();
    }

    /**
     * Create an instance of {@link SMC.Facts }
     * 
     */
    public SMC.Facts createSMCFacts() {
	return new SMC.Facts();
    }

    /**
     * Create an instance of {@link EventsType }
     * 
     */
    public EventsType createEventsType() {
	return new EventsType();
    }

    /**
     * Create an instance of {@link PlayerBindingType.Roles }
     * 
     */
    public PlayerBindingType.Roles createPlayerBindingTypeRoles() {
	return new PlayerBindingType.Roles();
    }

    /**
     * Create an instance of {@link RoleLinkedFactType.AcquisitionRegime }
     * 
     */
    public RoleLinkedFactType.AcquisitionRegime createRoleLinkedFactTypeAcquisitionRegime() {
	return new RoleLinkedFactType.AcquisitionRegime();
    }

    /**
     * Create an instance of {@link RoleLinkedFactType.ProvisionRegime }
     * 
     */
    public RoleLinkedFactType.ProvisionRegime createRoleLinkedFactTypeProvisionRegime() {
	return new RoleLinkedFactType.ProvisionRegime();
    }

    /**
     * Create an instance of {@link TaskRefsType }
     * 
     */
    public TaskRefsType createTaskRefsType() {
	return new TaskRefsType();
    }

    /**
     * Create an instance of {@link TaskRefType }
     * 
     */
    public TaskRefType createTaskRefType() {
	return new TaskRefType();
    }

    /**
     * Create an instance of {@link MessageType }
     * 
     */
    public MessageType createMessageType() {
	return new MessageType();
    }

    /**
     * Create an instance of {@link ContractType.Types }
     * 
     */
    public ContractType.Types createContractTypeTypes() {
	return new ContractType.Types();
    }

    /**
     * Create an instance of {@link ProcessDefinitionsType }
     * 
     */
    public ProcessDefinitionsType createProcessDefinitionsType() {
	return new ProcessDefinitionsType();
    }

    /**
     * Create an instance of {@link EventType }
     * 
     */
    public EventType createEventType() {
	return new EventType();
    }

    /**
     * Create an instance of {@link SMC.Contracts }
     * 
     */
    public SMC.Contracts createSMCContracts() {
	return new SMC.Contracts();
    }

    /**
     * Create an instance of {@link ContractLinkedFactType }
     * 
     */
    public ContractLinkedFactType createContractLinkedFactType() {
	return new ContractLinkedFactType();
    }

    /**
     * Create an instance of {@link ProcessDefinitionType }
     * 
     */
    public ProcessDefinitionType createProcessDefinitionType() {
	return new ProcessDefinitionType();
    }

    /**
     * Create an instance of {@link MessageAnalyzersType }
     * 
     */
    public MessageAnalyzersType createMessageAnalyzersType() {
	return new MessageAnalyzersType();
    }

    /**
     * Create an instance of {@link InMsgType }
     * 
     */
    public InMsgType createInMsgType() {
	return new InMsgType();
    }

    /**
     * Create an instance of {@link SrcMsgsType }
     * 
     */
    public SrcMsgsType createSrcMsgsType() {
	return new SrcMsgsType();
    }

    /**
     * Create an instance of {@link OperationType }
     * 
     */
    public OperationType createOperationType() {
	return new OperationType();
    }

    /**
     * Create an instance of {@link ContractType.LinkedFacts }
     * 
     */
    public ContractType.LinkedFacts createContractTypeLinkedFacts() {
	return new ContractType.LinkedFacts();
    }

    /**
     * Create an instance of {@link PlayerBindingType }
     * 
     */
    public PlayerBindingType createPlayerBindingType() {
	return new PlayerBindingType();
    }

    /**
     * Create an instance of {@link BehaviorTermRef }
     * 
     */
    public BehaviorTermRef createBehaviorTermRef() {
	return new BehaviorTermRef();
    }

    /**
     * Create an instance of {@link ConstraintType }
     * 
     */
    public ConstraintType createConstraintType() {
	return new ConstraintType();
    }

    /**
     * Create an instance of {@link ConstraintsType }
     * 
     */
    public ConstraintsType createConstraintsType() {
	return new ConstraintsType();
    }

    /**
     * Create an instance of {@link ResultMsgType }
     * 
     */
    public ResultMsgType createResultMsgType() {
	return new ResultMsgType();
    }

    /**
     * Create an instance of {@link PerformancePropertyType }
     * 
     */
    public PerformancePropertyType createPerformancePropertyType() {
	return new PerformancePropertyType();
    }

    /**
     * Create an instance of {@link MessageAnalyzerType }
     * 
     */
    public MessageAnalyzerType createMessageAnalyzerType() {
	return new MessageAnalyzerType();
    }

    /**
     * Create an instance of {@link SrcMsgType }
     * 
     */
    public SrcMsgType createSrcMsgType() {
	return new SrcMsgType();
    }

    /**
     * Create an instance of {@link MonitorRoleType }
     * 
     */
    public MonitorRoleType createMonitorRoleType() {
	return new MonitorRoleType();
    }

    /**
     * Create an instance of {@link SMC }
     * 
     */
    public SMC createSMC() {
	return new SMC();
    }

    /**
     * Create an instance of {@link TermType }
     * 
     */
    public TermType createTermType() {
	return new TermType();
    }

    /**
     * Create an instance of {@link TasksType }
     * 
     */
    public TasksType createTasksType() {
	return new TasksType();
    }

    /**
     * Create an instance of {@link RoleType.LinkedFacts }
     * 
     */
    public RoleType.LinkedFacts createRoleTypeLinkedFacts() {
	return new RoleType.LinkedFacts();
    }

    /**
     * Create an instance of {@link ContractType.Monitors }
     * 
     */
    public ContractType.Monitors createContractTypeMonitors() {
	return new ContractType.Monitors();
    }

    /**
     * Create an instance of {@link FactType.Attributes }
     * 
     */
    public FactType.Attributes createFactTypeAttributes() {
	return new FactType.Attributes();
    }

    /**
     * Create an instance of {@link RoleType }
     * 
     */
    public RoleType createRoleType() {
	return new RoleType();
    }

}
