//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.01 at 06:11:07 PM EST 
//

package au.edu.swin.ict.road.xml.bindings;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for OutMsgType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="OutMsgType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Operation" type="{http://www.swin.edu.au/ict/road/term}OperationType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="deliveryType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="isResponse" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OutMsgType", propOrder = { "operation" })
public class OutMsgType {

    @XmlElement(name = "Operation", namespace = "http://www.ict.swin.edu.au/serendip/types", required = true)
    protected OperationType operation;
    @XmlAttribute
    protected String deliveryType;
    @XmlAttribute
    protected Boolean isResponse;

    /**
     * Gets the value of the operation property.
     * 
     * @return possible object is {@link OperationType }
     * 
     */
    public OperationType getOperation() {
	return operation;
    }

    /**
     * Sets the value of the operation property.
     * 
     * @param value
     *            allowed object is {@link OperationType }
     * 
     */
    public void setOperation(OperationType value) {
	this.operation = value;
    }

    /**
     * Gets the value of the deliveryType property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDeliveryType() {
	return deliveryType;
    }

    /**
     * Sets the value of the deliveryType property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setDeliveryType(String value) {
	this.deliveryType = value;
    }

    /**
     * Gets the value of the isResponse property.
     * 
     * @return possible object is {@link Boolean }
     * 
     */
    public boolean isIsResponse() {
	if (isResponse == null) {
	    return false;
	} else {
	    return isResponse;
	}
    }

    /**
     * Sets the value of the isResponse property.
     * 
     * @param value
     *            allowed object is {@link Boolean }
     * 
     */
    public void setIsResponse(Boolean value) {
	this.isResponse = value;
    }

}
