//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.01 at 06:11:07 PM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.ict.swin.edu.au/serendip/types")
package au.edu.swin.ict.road.xml.bindings;

