//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.01 at 06:11:07 PM EST 
//

package au.edu.swin.ict.road.xml.bindings;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for ProcessDefinitionType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="ProcessDefinitionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CoS" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CoT" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BehaviorTermRefs" type="{http://www.ict.swin.edu.au/serendip/types}BehaviorTermRef"/>
 *         &lt;element name="Constraints" type="{http://www.ict.swin.edu.au/serendip/types}ConstraintsType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="descr" type="{http://www.w3.org/2001/XMLSchema}string" default="Description" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProcessDefinitionType", propOrder = { "coS", "coT",
	"behaviorTermRefs", "constraints" })
public class ProcessDefinitionType {

    @XmlElement(name = "CoS", namespace = "http://www.ict.swin.edu.au/serendip/types", required = true)
    protected String coS;
    @XmlElement(name = "CoT", namespace = "http://www.ict.swin.edu.au/serendip/types", required = true)
    protected String coT;
    @XmlElement(name = "BehaviorTermRefs", namespace = "http://www.ict.swin.edu.au/serendip/types", required = true)
    protected BehaviorTermRef behaviorTermRefs;
    @XmlElement(name = "Constraints", namespace = "http://www.ict.swin.edu.au/serendip/types")
    protected ConstraintsType constraints;
    @XmlAttribute(required = true)
    protected String id;
    @XmlAttribute
    protected String descr;

    /**
     * Gets the value of the coS property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCoS() {
	return coS;
    }

    /**
     * Sets the value of the coS property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCoS(String value) {
	this.coS = value;
    }

    /**
     * Gets the value of the coT property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCoT() {
	return coT;
    }

    /**
     * Sets the value of the coT property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setCoT(String value) {
	this.coT = value;
    }

    /**
     * Gets the value of the behaviorTermRefs property.
     * 
     * @return possible object is {@link BehaviorTermRef }
     * 
     */
    public BehaviorTermRef getBehaviorTermRefs() {
	return behaviorTermRefs;
    }

    /**
     * Sets the value of the behaviorTermRefs property.
     * 
     * @param value
     *            allowed object is {@link BehaviorTermRef }
     * 
     */
    public void setBehaviorTermRefs(BehaviorTermRef value) {
	this.behaviorTermRefs = value;
    }

    /**
     * Gets the value of the constraints property.
     * 
     * @return possible object is {@link ConstraintsType }
     * 
     */
    public ConstraintsType getConstraints() {
	return constraints;
    }

    /**
     * Sets the value of the constraints property.
     * 
     * @param value
     *            allowed object is {@link ConstraintsType }
     * 
     */
    public void setConstraints(ConstraintsType value) {
	this.constraints = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getId() {
	return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setId(String value) {
	this.id = value;
    }

    /**
     * Gets the value of the descr property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDescr() {
	if (descr == null) {
	    return "Description";
	} else {
	    return descr;
	}
    }

    /**
     * Sets the value of the descr property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setDescr(String value) {
	this.descr = value;
    }

}
