//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.01 at 06:11:07 PM EST 
//

package au.edu.swin.ict.road.xml.bindings;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for RoleType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="RoleType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LinkedFacts" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Fact" type="{http://www.swin.edu.au/ict/road/role}RoleLinkedFactType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ManagementResponsibilities" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Tasks" type="{http://www.ict.swin.edu.au/serendip/types}TasksType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RoleType", namespace = "http://www.swin.edu.au/ict/road/role", propOrder = {
	"description", "linkedFacts", "managementResponsibilities", "tasks" })
public class RoleType {

    @XmlElement(name = "Description")
    protected String description;
    @XmlElement(name = "LinkedFacts")
    protected RoleType.LinkedFacts linkedFacts;
    @XmlElement(name = "ManagementResponsibilities")
    protected String managementResponsibilities;
    @XmlElement(name = "Tasks")
    protected TasksType tasks;
    @XmlAttribute(required = true)
    protected String id;
    @XmlAttribute
    protected String name;

    /**
     * Gets the value of the description property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDescription() {
	return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setDescription(String value) {
	this.description = value;
    }

    /**
     * Gets the value of the linkedFacts property.
     * 
     * @return possible object is {@link RoleType.LinkedFacts }
     * 
     */
    public RoleType.LinkedFacts getLinkedFacts() {
	return linkedFacts;
    }

    /**
     * Sets the value of the linkedFacts property.
     * 
     * @param value
     *            allowed object is {@link RoleType.LinkedFacts }
     * 
     */
    public void setLinkedFacts(RoleType.LinkedFacts value) {
	this.linkedFacts = value;
    }

    /**
     * Gets the value of the managementResponsibilities property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getManagementResponsibilities() {
	return managementResponsibilities;
    }

    /**
     * Sets the value of the managementResponsibilities property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setManagementResponsibilities(String value) {
	this.managementResponsibilities = value;
    }

    /**
     * Gets the value of the tasks property.
     * 
     * @return possible object is {@link TasksType }
     * 
     */
    public TasksType getTasks() {
	return tasks;
    }

    /**
     * Sets the value of the tasks property.
     * 
     * @param value
     *            allowed object is {@link TasksType }
     * 
     */
    public void setTasks(TasksType value) {
	this.tasks = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getId() {
	return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setId(String value) {
	this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getName() {
	return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setName(String value) {
	this.name = value;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained
     * within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Fact" type="{http://www.swin.edu.au/ict/road/role}RoleLinkedFactType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "fact" })
    public static class LinkedFacts {

	@XmlElement(name = "Fact", required = true)
	protected List<RoleLinkedFactType> fact;

	/**
	 * Gets the value of the fact property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list
	 * will be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the fact property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getFact().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link RoleLinkedFactType }
	 * 
	 * 
	 */
	public List<RoleLinkedFactType> getFact() {
	    if (fact == null) {
		fact = new ArrayList<RoleLinkedFactType>();
	    }
	    return this.fact;
	}

    }

}
