//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.01 at 06:11:07 PM EST 
//

package au.edu.swin.ict.road.xml.bindings;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for TaskType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="TaskType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Out" type="{http://www.ict.swin.edu.au/serendip/types}OutMsgType" minOccurs="0"/>
 *         &lt;element name="In" type="{http://www.ict.swin.edu.au/serendip/types}InMsgType" minOccurs="0"/>
 *         &lt;element name="SrcMsgs" type="{http://www.ict.swin.edu.au/serendip/types}SrcMsgsType" minOccurs="0"/>
 *         &lt;element name="ResultMsgs" type="{http://www.ict.swin.edu.au/serendip/types}ResultMsgsType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="msgAnalyser" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="isMsgDriven" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TaskType", propOrder = { "out", "in", "srcMsgs", "resultMsgs" })
public class TaskType {

    @XmlElement(name = "Out", namespace = "http://www.ict.swin.edu.au/serendip/types")
    protected OutMsgType out;
    @XmlElement(name = "In", namespace = "http://www.ict.swin.edu.au/serendip/types")
    protected InMsgType in;
    @XmlElement(name = "SrcMsgs", namespace = "http://www.ict.swin.edu.au/serendip/types")
    protected SrcMsgsType srcMsgs;
    @XmlElement(name = "ResultMsgs", namespace = "http://www.ict.swin.edu.au/serendip/types")
    protected ResultMsgsType resultMsgs;
    @XmlAttribute
    protected String id;
    @XmlAttribute
    protected String msgAnalyser;
    @XmlAttribute(required = true)
    protected boolean isMsgDriven;

    /**
     * Gets the value of the out property.
     * 
     * @return possible object is {@link OutMsgType }
     * 
     */
    public OutMsgType getOut() {
	return out;
    }

    /**
     * Sets the value of the out property.
     * 
     * @param value
     *            allowed object is {@link OutMsgType }
     * 
     */
    public void setOut(OutMsgType value) {
	this.out = value;
    }

    /**
     * Gets the value of the in property.
     * 
     * @return possible object is {@link InMsgType }
     * 
     */
    public InMsgType getIn() {
	return in;
    }

    /**
     * Sets the value of the in property.
     * 
     * @param value
     *            allowed object is {@link InMsgType }
     * 
     */
    public void setIn(InMsgType value) {
	this.in = value;
    }

    /**
     * Gets the value of the srcMsgs property.
     * 
     * @return possible object is {@link SrcMsgsType }
     * 
     */
    public SrcMsgsType getSrcMsgs() {
	return srcMsgs;
    }

    /**
     * Sets the value of the srcMsgs property.
     * 
     * @param value
     *            allowed object is {@link SrcMsgsType }
     * 
     */
    public void setSrcMsgs(SrcMsgsType value) {
	this.srcMsgs = value;
    }

    /**
     * Gets the value of the resultMsgs property.
     * 
     * @return possible object is {@link ResultMsgsType }
     * 
     */
    public ResultMsgsType getResultMsgs() {
	return resultMsgs;
    }

    /**
     * Sets the value of the resultMsgs property.
     * 
     * @param value
     *            allowed object is {@link ResultMsgsType }
     * 
     */
    public void setResultMsgs(ResultMsgsType value) {
	this.resultMsgs = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getId() {
	return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setId(String value) {
	this.id = value;
    }

    /**
     * Gets the value of the msgAnalyser property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getMsgAnalyser() {
	return msgAnalyser;
    }

    /**
     * Sets the value of the msgAnalyser property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setMsgAnalyser(String value) {
	this.msgAnalyser = value;
    }

    /**
     * Gets the value of the isMsgDriven property.
     * 
     */
    public boolean isIsMsgDriven() {
	return isMsgDriven;
    }

    /**
     * Sets the value of the isMsgDriven property.
     * 
     */
    public void setIsMsgDriven(boolean value) {
	this.isMsgDriven = value;
    }

}
