//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.01 at 06:11:07 PM EST 
//

package au.edu.swin.ict.road.xml.bindings;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for TaskRefType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="TaskRefType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="Id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="preEP" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="postEP" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="performanceVal" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TaskRefType")
public class TaskRefType {

    @XmlAttribute(name = "Id", required = true)
    protected String id;
    @XmlAttribute
    protected String preEP;
    @XmlAttribute
    protected String postEP;
    @XmlAttribute
    protected String performanceVal;
    @XmlAttribute
    protected String type;

    /**
     * Gets the value of the id property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getId() {
	return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setId(String value) {
	this.id = value;
    }

    /**
     * Gets the value of the preEP property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getPreEP() {
	return preEP;
    }

    /**
     * Sets the value of the preEP property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setPreEP(String value) {
	this.preEP = value;
    }

    /**
     * Gets the value of the postEP property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getPostEP() {
	return postEP;
    }

    /**
     * Sets the value of the postEP property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setPostEP(String value) {
	this.postEP = value;
    }

    /**
     * Gets the value of the performanceVal property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getPerformanceVal() {
	return performanceVal;
    }

    /**
     * Sets the value of the performanceVal property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setPerformanceVal(String value) {
	this.performanceVal = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getType() {
	return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setType(String value) {
	this.type = value;
    }

}
